version: '3.8'

services:
  python_app:
    image: python:3.11-slim
    container_name: python_with_polars
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install --no-cache-dir . && python test.py"
    environment:
      - PYTHONUNBUFFERED=1
